# Generated by Django 5.1.1 on 2025-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name1',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='name2',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='text1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
