# Generated by Django 5.2.6 on 2025-09-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_text_image1_text_image2_text_image3_text_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name1_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name1_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name2_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name2_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text1_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text1_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text2_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text2_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='name1_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='name1_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='name2_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='name2_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='name3_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='name3_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='name_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='name_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text1_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text1_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text2_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text2_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text3_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text3_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
