# Generated by Django 5.2.6 on 2025-09-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_about_name1_en_about_name1_ru_about_name2_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name1_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name1_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name2_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name2_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text1_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text1_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text2_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text2_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text_ru',
        ),
    ]
