# Generated by Django 6.1 on 2026-09-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='image',
            field=models.ImageField(upload_to='text/'),
        ),
        migrations.AlterField(
            model_name='text',
            name='image1',
            field=models.ImageField(upload_to='text/'),
        ),
        migrations.AlterField(
            model_name='text',
            name='image2',
            field=models.ImageField(upload_to='text/'),
        ),
        migrations.AlterField(
            model_name='text',
            name='image3',
            field=models.ImageField(upload_to='text/'),
        ),
    ]
